---
title: "Publications"
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<style>
d-title, d-byline {
  display: none
}
</style>

<br>

# Publications

Authors that are <u>**bold and underlined**</u> indicate URBANxNATURE Lab members

J Hewitt, G Wilson-Henjum, JC Chandler, AT Phillips, DG Diel, WD Walter, A Baker, J Høy-Petersen, G Bastille-Rousseau, T Kishimoto, G Wittemyer, J Alder, S Hathaway, KR Manlove, **<u>T Gallo</u>**, J Mullinax, **<u>C Coriell</u>**, **<u>M Payne</u>**, ME Craft, TJ Garwood, TM Wolf, MA Diuk-Wasser, MC VanAcker, L Dudley Plimpton, MQ Wilber, D Grove, J Koseiwska, LI Muller, KM Pepin. 2025. Evaluation of SARS-CoV-2 antibody detection methods for wild Cervidae. Preventive Veterinary Medicine. 106522

Devarajan, K., Fidino, M., Farris, Z. J., Adalsteinsson, S. A., Andrade- Ponce, G., Angstmann, J. L., Anthonysamy, W., Aquino, J., Asefu, A., Avila, B., Bailey, L. L., de Sousa, L. M., de Frias Barreto, B. M., Barton, O., Bates, C. E., Guimarães Beltrão, M., Bird, T., Biro, E. G., Bisi, F., Bohórquez, D., Boyce, M., Brashares, J. S., Bullington, G., Burns, P., Burr, J., Butler, A. R., Calhoun, K. L., Trung Cao, T., Casado, N., Cepeda-Duque, J. C., Cepek, J. D., Garcia Chiarello, A., Collins, M., Cordeiro-Estrela, P., Costa, S., Cremonesi, G., Cristescu, B., Cruz, P., de Albuquerque, A. C. F., De Angelo, C., de Campos, C. B., de Sena, L. M. M., Di Bitetti, M., de Matos Dias, D., Diefenbach, D., Doherty, T. S., dos Santos, T. P., Teixeira Duarte, G., Eppley, T. M., Erb, J., Franco Esteves, C., Evans, B., Falcão, M. L. M., Fernandes-Ferreira, H., Fieberg, J. R., de Souza Filho, L. C. F., Fisher, J., Fortin, M.-J., Gale, G. A., <u>**Gallo, T.**</u>, Ganoe, L. S., Garcia-Anleu, R., Gaynor, K. M., Gelmi-Candusso, T. A., Gichuru, P. N., Gomez, Q., Green, A. M., Neves Guimarães, L., Haight, J. D., Harris, L. R., Hawn, Z. D., Heiman, J., Quoc Hoang, H., Huebner, S., Iannarilli, F., Eugenia Iezzi, M., Ivan, J. S., Jaspers, K. J., Jordan, M. J., Kamilar, J., Kane, M., Karimi, M. H., Kelly, M., Kohl, M. T., Kuvlesky, W. P., Ladle, A., Larson, R. N., Tan Le, Q., Le, D., Son Le, V., Lehrer, E. W., Lendrum, P. E., Lewis, J., Link, A., Lizcano, D. J., Lombardi, J. V., Long, R., López-Tello, E., Lugarini, C., Lugo, D., MacKay, P., Madadi, M., Magalhães, R. A., Magle, S. B., NA, Mandujano, S., Marchenkova, T., Henrique Marinho, P., Marker, L., Martinez Pardo, J., Martinoli, A., Massara, R. L., Masseloux, J., Matiukhina, D., Mayer, A., Mazariegos, L., McBride, A., McClung, M. R., McInturff, A., McPhail, D., Mertl, A., Middaugh, C. R., Miller, D., Mills, D., Miquelle, D., Miritis, V., Moll, R. J., Molnár, P., Montgomery, R. A., Morelli, T. L., Mortelliti, A., Muelle, R. I., Mukhacheva, A. S., Mullen, K., Murphy, A., Nepomuceno, V., Ngoprasert, D., Nguyen, A., Van Nguyen, T., Van Nguyen, T., Anh Nguyen Quang, H., Nipko, R., Nobre, A. C. C., Northrup, J., Owen, M. A., Paglia, A. P., Palmer, M. S., Palomo-Munoz, G., Pardo, L. E., Parks, C., de Oliveira Paschoal, A. M., Patterson, B., Paviolo, A., Pejchar, L., Pendergast, M. E., Perotto-Baldivieso, H. L., Petrov, T., Poisson, M. K. P., Polli, D. J., Pourmirzai, M., Reebin, A., Remine, K. R., Rich, L., Richardson, C. S., Robino, F., Rocha, D. G., Rocha, F. L., Rodrigues, F., Rohnke, A. T., Ryan, T. J., Salsbury, C. M., Sander, H. A., da Cruz Santos-Cavalcante, N. M., Sekercioglu, C. H., Seryodkin, I., Setiawan, D. H., Shadloo, S., Shahhosseini, M., Shannon, G., Shier, C. J., Smith, G. B., Snyder, T., Sollmann, R., Sparks, K. L., Sribuarod, K., St. Clair, C. C., Stankowich, T., Steinmetz, R., Stevenson, C. J., Sunarto, Surasinghe, T. D., Sutyrina, S. V., Swaisgood, R. R., Taktehrani, A., Thapa, K., Thorton, M., Tilker, A., Tobler, M. W., Van Bang, T., Tucker, J., Van Horn, R. C., Vargas- Soto, J. S., Velásquez-C, K. L., Venter, J., Venticinque, E. M., Verschueren, S., Wampole, E., J Watchorn, D., Wearn, O. R., Weiss, K. C., Welschen, A., Widodo, F. A., Williamson, J., Wilting, A., Wittemeyer, G., Zavaleta, A., Zellmer, A. J., and Gerber, B. D. 2025. When the wild things are: defining mammalian diel activity and plasticity. Science Advances. 11, eado3843 [PDF](publications/sciadv.ado3843.pdf)

Rooney, B., Kays, R., Cove, M.V., Jensen, A., Goldstein, B.R., Pate, C., Castiblanco, P., Abell, M.E., Adley, J., Agenbroad, B., Ahlers, A.A., Alexander, P.D., Allen, D., Allen, M.L., Alston, J.M., Alyetama, M., Anderson, T.L., Andrade, R., Anhalt-Depies, C., Appel, C.L., Armendariz, L., Ayers, C.R., Baird, A.B., Bak, C., Bandler, G., Barding, E.E., Barr, E.G., Baruzzi, C., Bashaw, K., Beers, S.C., Belant, J.L., Bell, E., Benson, J.F., Berg, A., Bergman, D.L., Bernhardt, B.M., Bethel, M.A., Bird, T., Bishop, A.B., Bogan, D.A., Brandt, L., Brandt, L.C., Branney, A.B., Bratton, C., Bresnan, C.E., Brooke, J.M., Buchholtz, E.K., Buderman, F., Burnett, A.D., Burns, E.E., Byrd, D.A., Cannella, S.A., Carey, K.A., Carlile, W.A., Carter, K.L., Cassidy, B.J., Castro-Arellano, I., Cendejas-Zarelli, S., Chatterjee, N., Cheeseman, A.E., Chevalier, C., Chitwood, M.C., Chrysafis, P., Collier, B.A., Collins, D.P., Compton, J.A., Cone, R., Conner, L.M., Cook, B.L., Cosby, O.G., Coster, S.S., Crupi, A.P., Darracq, A.K., Davenport, J.M., Davis, D., Davis, D.R., Davis, M.L., Davis, R.J., DeGregorio, B.A., Deshwal, A., Dougherty, K.D., Drauglis, A., Durbin, C.J., Edelman, A.J., Elder, V., Eller, B., Ellington, E.H., Ellis-Felege, S.N., Ellison, C.N., Fantle-Lepczyk, J.E., Farr, J.J., Farris, Z.J., Finnegan, S.P., Fisher-Reid, M.C., Flaherty, E.A., Franzoi Dri, G., Fritts, S., Fuller, J., <u>**Gallo, T.**</u>, Ganoe, L.S., Ganong, C.N., Garibay, R., Gerber, B.D., Gerraty, F.D., Giery, S.T., Gilyot, S.M., Glasscock, J.L., Goldfarb, B., Good, L.E., Granados, G., Green, A.M., Grewal, J.K., Grusenmeyer, A., Guthrie, J.M., Hallett, M.T., Hansen, C., Hansen, L.P., Hanson, C., Harrity, E.J., Hasstedt, S.C.M., Hebblewhite, M., <u>**Herrera, D.J.**</u>, Holland, A., Humphreys, B.R., Island, H.D., Jack, A.R., Johansson, E.P., Johnson, A.M., Johnson, L., Johnstone-Yellin, T.L., Jorge, M.L.S.P., Kahano, W., Kinsey, M.A., Klossing, B.E., Knowles, T.W., Koeck, M.M., Koprowski, J.L., Kuhn, K.M., Kuprewicz, E.K., Lafferty, D.J.R., Lamberton-Moreno, J.A., Land, T.J., Langston, A.M., LaPoint, S., Largent, E.N., Lashley, M.A., Lathrop, R.G., Lee, T.E., Jr, Lepczyk, C.A., Lesmeister, D.B., Leung, C., Lombardi, J.V., Long, R., Lonsinger, R.C., Lord, I., Madere, S.S., Maher, S.P., Mallinoff, J.A., Martinez, A., Mason, D.S., Mathewson, H.A., Mayer, A.E., McCarthy, K.P., McCracken, S.F., McDonald, B., McGarry, B., McMurry, S.T., McTigue, L.E., Mena, B.M., Mercer, M., Merz, M.R., Millar, S., Miller, G.D., Millspaugh, J.J., Moll, R.J., Mong, T.W., Monzón, J.D., Moore, J.C., Mortelliti, A., Mote, K.W., Mullen, K., Mychajliw, A., Nagy, C., Neiswenter, S.A., Neyland, D.R., Nicholson, L.P., O'Mara, M.T., O'Neill, B.J., Olson, E.A., Orgill, M.J., Palomo-Munoz, G., Parsons, S.M., Patrick, L.E., Patterson, J.R., Pearce, D.L., Pendergast, M.E., Perla, B.S., Petroelje, T.R., Pliske, H., Poisson, M.K.P., Price, M.R., Proctor, M.D., Proudman, N.J., Rachlow, J.L., Ramos, R.E., Reabold, M., Redinger, J., Reed, A.E., Rega-Brodsky, C.C., Rehm, E., Remine, K.R., Rentz, M.S., Ridder, E., Risch, D.R., Robbins, L.L., Roemer, J.P., Romero, A., Rota, C., Schalk, C.M., Scholten, B.D., Scott, C.L., Scurlock, B.M., Sergeyev, M., Severud, W.J., Sevin, J., Shamon, H., Sharp, C., Shaw, M., Siverls-Dunham, V., Smith, A.B., Smith, D.S., Snider, M.H., Sossover, D.A., Sovie, A.R., Sparks, J.A., Speiser, J., Springer, M.T., Spurlin, J.L., Steinkamp, E.A., Stenglein, J.L., Stewart Kloker, J., Stitzman, C.M., Stokes, M., Stringer, K., Stutzman, J., Sullins, D.S., Sullivan, C., Sullivan, N.B., Tanner, E.P., Tanner, A.M., Thornock, E.B., Titus, J., Tleimat, J.M., Toomey, K., Toussaint, L.T., Uribe, M., Van der Merwe, M., Van Parys, D.J., Vanek, J.P., Varner, J., Walker, B.V., Wallace, C., Ward, D., Warner, B.H., Warren, D.T., Wasdin, J.R., Webb, S.L., Wehr, K.L., Wehr, N.H., Weigel, E.G., Werdel, T.J., Whipple, L.S., Whittier, C.A., Wiersema, C., Wilson, A.M., Wilson, M.F.H., Wolf, A.J., Wolford, J.P., Wolfson, D.W., Woolsey, D.J., Wuensch, M.A., Xu, G., Yurewicz, K.L., Zancho, V., Zimova, M., Zorn, A. and McShea, W.J. 2025, SNAPSHOT USA 2019–2023: The First Five Years of Data From a Coordinated Camera Trap Survey of the United States. Global Ecology Biogeography, 34: e13941. [PDF](publications/Snapshop_2025.pdf)

**<u>Palomo-Munoz, G.</u>**, M Fidino, TJ Werdel, CW Piper, **<u>T Gallo</u>**, MS Peek, AM Ricketts, and AA Ahlers. 2024. Mesopredators Have Differing Influences on Prey Habitat Use and Diel Activity in a Multipredator Landscape. Ecosphere 15(9): e70006. [PDF](publications/Ecosphere-2024-Palomo‐Munoz.pdf)

**<u>Collins, M.K.</u>**, **<u>T. Gallo</u>**. 2024. Legacy effects of housing segregation on urban mammal communities in Washington, D.C., USA. Urban Ecosystems. [PDF](publications/Collins_Gallo_2024.pdf)

**<u>Herrera, D.J.</u>**, M. Fidino, D. Luther, J.M. Mullinax, **<u>T. Gallo</u>**. 2024. Historical park planning is associated with modern-day patterns of bird diversity in cities. Landscape and Urban Planning, 249, 105132. [PDF](publications/Herrera_etal_2024_LAND.pdf)

Hila Shamon, Roi Maor,  Michael V. Cove,  Roland Kays,  Jessie Adley,  Peter D. Alexander,  David N. Allen,  Maximilian L. Allen,  Cara L. Appel,  Evan Barr,  Erika L. Barthelmess,  Carolina Baruzzi,  Kelli Bashaw,  Guillaume Bastille-Rousseau,  Madison E. Baugh,  Jerrold Belant,  John F. Benson,  Bethany A. Bespoyasny,  Tori Bird,  Daniel A. Bogan,  LaRoy S. E. Brandt,  Claire E. Bresnan,  Jarred M. Brooke,  Frances E. Buderman,  Suzannah G. Buzzell,  Amanda E. Cheeseman,  M. Colter Chitwood,  Petros Chrysafis,  <u>**Merri K. Collins**</u>,  D. Parks Collins,  Justin A. Compton,  L. Mike Conner,  Olivia G. Cosby,  Stephanie S. Coster,  Benjamin Crawford,  Anthony P. Crupi,  Andrea K. Darracq,  Miranda L. Davis,  Brett A. DeGregorio,  Kimberly L. Denningmann,  Kyle D. Dougherty,  Ace Driver,  Andrew J. Edelman,  E. Hance Ellington,  Susan N. Ellis-Felege,  Caroline N. Ellison,  Jean E. Fantle-Lepczyk,  Zach J. Farris,  Jorie Favreau,  Pilar Fernandez,  M. Caitlin Fisher-Reid,  Matthew C. Fitzpatrick,  Elizabeth A. Flaherty,  Tavis D. Forrester,  Sarah R. Fritts,  <u>**Travis Gallo**</u>,  Brian D. Gerber,  Sean T. Giery,  Jessica L. Glasscock,  Alex D. Gonatas,  Anna C. Grady,  Austin M. Green,  Tremaine Gregory,  Noel Griffin,  Robert H. Hagen,  Christopher P. Hansen,  Lonnie P. Hansen,  Steven C. Hasstedt,  Haydée Hernández-Yáñez,  <u>**Daniel J. Herrera**</u>,  Robert V. Horan III,  Victoria L. Jackson,  Luanne Johnson,  Mark J. Jordan,  Willaine Kahano,  Joseph Kiser,  Travis W. Knowles,  Molly M. Koeck,  Caroline Koroly,  Kellie M. Kuhn,  Erin K. Kuprewicz,  Diana J. R. Lafferty,  Scott D. LaPoint,  Marcus Lashley,  Richard G. Lathrop,  Thomas E. Lee Jr.,  Christopher A. Lepczyk,  Damon B. Lesmeister,  Jason V. Lombardi,  Robert A. Long,  Robert C. Lonsinger,  Paula MacKay,  Sean P. Maher,  David S. Mason,  Joshua J. Millspaugh,  Remington J. Moll,  Jessica B. Moon,  Alessio Mortelliti,  Alexis M. Mychajliw,  Christopher M. Nagy,  Sean A. Neiswenter,  Dana L. Nelson,  Claire E. Nemes,  Clayton K. Nielsen,  Elizabeth Olson,  M. Teague O'Mara,  Brian J. O'Neill,  Blake R. Page,  Elizabeth Parsons,  Brent S. Pease,  Mary E. Pendergast,  Mike Proctor,  Heather Quick,  Christine C. Rega-Brodsky,  Michael S. Rentz,  Kylie Rezendes,  Daric Rich,  Derek R. Risch,  Andrea Romero,  Brigit R. Rooney,  Christopher T. Rota,  Corey A. Samples,  Christopher M. Schalk,  Çağan H. Sekercioğlu,  Maksim Sergeyev,  Austin B. Smith,  Daniel S. Smith,  Jinelle H. Sperry,  Jennifer L. Stenglein,  Michael K. Stokes,  Johnathon S. Stutzman,  Kimberly R. Todd,  John P. Vanek,  Wren Varga,  Zachary M. Wardle,  Stephen L. Webb,  Nathaniel H. Wehr,  Laura S. Whipple,  Christopher A. Whittier,  Jane S. Widness,  Jacque Williamson,  Andrew M. Wilson,  Alexander J. Wolf,  Marketa Zimova,  Adam S. Zorn,  William J. McShea. 2024. SNAPSHOT USA 2021: A Third Coordinated National Camera Trap Survey of the United States.” Ecology: e4318 [PDF](publications/Ecology_2024_SNAPSHOT.pdf)

Fusco, N.A., J.P. Vanek, B.J. Cosentino, J.P. Gibbs, A.J. Blumenfeld, M.L. Allen, J. Boettner, K. Briggs, E.J. Carlen, <u>**M. Collins**</u>, C. Dennison, D. DiGiacopo, A-P.D. Picard, J. Edmonson, C. Fisher-Reid, R. Fyffe, <u>**T. Gallo**</u>, A. Grant, W. Harbold, S. Heard, D. Lafferty, R. Lehtinen, S. Marino, J.E. McDonald, A. Mortelliti, M. Murray, A. Newman, K. Oswald, C. Ott-Conn, J. Richardson, R. Rimbach, P. Salaman, M. Steele, M. Stothart, M.C. Urban, K. Vandergrift, S. Vanderluit, L. Vezina, and A. Caccone. 2023. Population genomic structure of a widespread, urban-dwelling mammal; The Eastern gray squirrel (*Sciurus carolinensis*). Molecular Ecology, 33, e17230 [PDF](publications/MolecularEcology_2023_Fusco.pdf)

Anderson, T., <u>**D. Herrera**</u>, F. Mireku, K. Barner, A. Kokkinakis, H. Dao, A. Webber, A.D. Merida, <u>**T. Gallo**</u>, M. Pierobon. 2023. Geographical Variation in Social Determinants of Female Breast Cancer Mortality Across US Counties. JAMA Network Open 6(9):e2333618 [PDF](publications/anderson_2023.pdf)

Schell CJ, NC Harris, S Des Roches, <u>**T Gallo**</u>, M Lambert. 2023. Biodiversity for the People: Future Directions for Urban Biodiversity Conservation in Urban Biodiversity and Equity: Justice-Centered Conservation in Cities. Oxford University Press.

Haight, Jeffrey D.; Sharon J. Hall; Mason Fidino; Solny A. Adalsteinsson; Adam A. Ahlers; Julia Angstmann; Whitney J. B. Anthonysamy; Elizabeth Biro; <u>**Merri K. Collins**</u>; Barbara Dugelby; <u>**Travis Gallo**</u>; Austin M. Green; Laura Hartley; Mark J. Jordan; Cria A. M. Kay; Elizabeth W. Lehrer; Robert A. Long; Brandon MacDougall; Seth B. Magle; Darren E. Minier; Chris Mowry; Maureen Murray; Kristina Nininger; Mary E. Pendergast; Katie R. Remine; Travis Ryan; Carmen Salsbury; Christopher J. Schell; Çagan Șekercioğlu; Catherine J. Shier; Kelly C. Simon; Colleen C. St. Clair; Theodore Stankowich; Cassondra J. Stevenson; Lisa Wayne; Dave Will; J. Williamson; Larry Wilson; Amanda J. Zellmer; Jesse S. Lewis 2023. Urbanization, climate, and species traits shape mammal communities from local to continental scales. Nature Ecology & Evolution 7, 1654–1666 [PDF](publications/Haight_et_al-2023-Nature_Ecology_&_Evolution.pdf)

Cervantes AM, RL Schooley, EW Lehrer, <u>**T Gallo**</u>, ML Allen, M Fidino, SB Magle. 2023. Carnivore coexistence in Chicago: niche partitioning of coyotes and red foxes. Urban Ecosystems 26, 1293–1307 [PDF](publications/Cervantes_etal_UE.pdf)

<u>**Herrera DJ**</u>, Cove MV, McShea WJ, Decker S, Flockhart DT, Moore SM, <u>**Gallo T**</u>. 2022. Spatial and temporal overlap of domestic cats (*Felis catus*) and native urban wildlife. Frontiers in Ecology and Evolution 10:1048585. [PDF](publications/Herrera_2022.pdf)

<u>**Gallo, T.**</u>, M. Fidino, B. Gerber, A.A. Ahlers, J.L. Angstmann, M. Amaya, A.L. Concilio, D. Drake, D. Gray, E.W. Lehrer, M.H. Murray, T.J. Ryan, C.C. St. Clair, C.M. Salsbury, H.A. Sander, T. Stankowich, J. Williamson, J.A. Belaire, K. Simon, Seth B. Magle. 2022. Mammals adjust diel activities across gradients of urbanization. eLife 11:e74756 [PDF](publications/elife-74756-v2.pdf)

<u>**Herrera DJ**</u>, Cove MV, McShea WJ, Flockhart DT, Decker S, Moore SM, <u>**Gallo T.**</u> 2022. Prey selection and predation behavior of free-roaming domestic cats (*Felis catus*) in an urban ecosystem: implications for urban cat management. Biological Conservation 268:109503 [PDF](publications/herrera_etal_2022_BiolCon.pdf)

Fidino, M., Bender, J., Limbrick, K., <u>**Gallo, T.**</u>, and Magle, S. B. 2022. Strolling through a century: recreating historical bird surveys to explore 100 years of change in an urban bird community. American Naturalist 199:159-167 [PDF](publications/Fidino_etal_StrollingThroughACentury.pdf)

Magle, S., Fidino, M., Sander, H., Rohnke, A. T., Larson, K. L., <u>**Gallo, T.**</u>, Kay, C. A. M., Lehrer, E. W., Murray, M. H., Adalsteinsson, S. A., Ahlers, A. A., Anthonysamy, W. J. B., Gramza, A. R., Green, A. M., Jordan, M. J., Lewis, J., Long, R. A., MacDougall, B., Pendergast, M. E., Remine, K., Simon, K. C., Cassady St. Clair, C., Shier, C. J., Stankowich, T., Stevenson, C. J., Zellmer, A. J., and Schell, C. J. 2021. Wealth and urbanization shape medium and large mammalian communities across North America. Global Change Biology 27: 5446-5459 [PDF](publications/Magle_2021_et_al_GCB_luxury.pdf)

<u>**Collins, M.**</u>, S.B. Magle, <u>**T. Gallo**</u>. 2021. Global trends in urban wildlife ecology and conservation. Biological Conservation 26:109236 [PDF](publications/Collins_Gallo_2021_BiolCons.pdf)

Lehrer, E.W, <u>**T. Gallo**</u>, M. Fidino, R.J. Kilgour, P.J. Wolff, S. Magle. 2021. Urban bat occupancy is highly influenced by noise and the location of water: Considerations for nature-based urban planning. Landscape and Urban Planning 210:104063. [PDF](publications/Lehrer_etal_2021_urban-bats.pdf)

Fidino, M., <u>**T. Gallo**</u>, E.W. Lehrer, M.H. Murray, C. Kay H.A. Sander, B. MacDougall, C.M. Salsbury, T.J. Ryan, J.L. Angstmann, J.A. Belaire, B. Dugelby, C. Schell, T. Stankowich, M. Amaya, D. Drake, S.H. Hursh, A.A. Ahlers, J. Williamson, L.M. Hartley, A.J. Zellmer, K. Simon, and S.B. Magle. 2021. Landscape-scale differences among cities alter common species’ responses to urbanization. Ecological Applications 31:e02253. [PDF](publications/fidino-et-al-occupancy-eap.pdf) | [COVER PHOTO](publications/eap.2292_coverphoto.pdf)

<u>**Ritzel, K.**</u> and <u>**T. Gallo**</u>. 2020. Behavior Change in Urban Mammals: A Systematic Review. Frontiers in Ecology and Evolution 8:576665. [PDF](publications/Ritzel_Gallo_2020_FrontEcolEvol.pdf)

<u>**\*Gallo**</u>, T., \*M. Fidino, E.W. Lehrer, S. Magle. 2019. Urbanization alters predator-avoidance behaviours. Journal of Animal Ecology 88:793-803. [PDF](publications/Gallo_et_al-2019-Journal_of_Animal_Ecology.pdf)  \*Both authors contributed equally

Potratz, E., J.S. Brown, <u>**T. Gallo**</u>, C. Anchor, R.M Santymire. 2019. Effects of demography and urbanization on stress and body condition of urban white-tailed deer. Urban Ecosystems. [PDF](publications/Potratz2019_Article_EffectsOfDemographyAndUrbaniza.pdf)

Magle, S.B., M. Fidino, E.W. Lehrer, <u>**T. Gallo**</u>, M.P. Mulligan, M.J. Ríos, A.A. Ahlers, J. Angstmann, A. Belaire, B. Dugelby, A. Gramza, L. Hartley, B. MacDougall, T. Ryan, C. Salsbury, H. Sander, C. Schell, K. Simon, D. Drake. 2019. Advancing urban wildlife research through a multi-city collaboration. Frontiers in Ecology and the Environment 17:232-239. [PDF](publications/Magle_etal_AdvancingUrbanWildlife.pdf)

<u>URBANxNATURE Lab Established in 2019</u>

Gallo, T. and M. Fidino. **2018**. Insight: Making wildlife welcome in urban areas. eLife 7:e41348. [PDF](publications/eLife.41348.pdf)

Gallo, T., E.W. Lehrer, M. Fidino, R.J. Kilgour, P.J. Wolff, S. Magle. **2018**. Need for multiscale planning for conservation of urban bats. Conservation Biology 32:638-647. [PDF](publications/Gallo_et_al-2018-Conservation_Biology.pdf)

Pejchar, L., T. Gallo, M. Hooten, G. Dailey. **2018**. Predicting effects of large-scale reforestation on native and exotic birds. Diversity and Distributions 24:811-819. [PDF](publications/pejchar_dd.pdf)

Gallo, T., M. Fidino, E.W. Lehrer, S. Magle. **2017**. Mammal diversity and metacommunity dynamics in urban green spaces: implications for urban wildlife conservation. Ecological Applications 27:2330–2341. [PDF](publications/galloetal_eap.pdf)

Gallo, T., L.T. Stinson, L. Pejchar. **2017**. Mitigation for energy development fails to mimic natural disturbance for birds and mammals. Biological Conservation. 212:39-47. [PDF](publications/Gallo_et_al_2017_biolcons.pdf)

Gallo, T. and L. Pejchar. **2017**. Woodland reduction and long-term change in breeding bird communities. Journal of Wildlife Management 81:259-268. [PDF](publications/gallo_jwmg.21188.pdf)

Farr, C., D. Bennett, S. Bombaci, T. Gallo, A. Mangan, T. Nogeire, H. Riedl. L. Stinson, K. Wilkins, L. Pejchar. **2017**. Addressing the gender gap in distinguished speakers at professional ecology conferences. Bioscience 67:464-468. [PDF](publications/Farr_etal_2017_BioScience.pdf)

Bombaci, S., T. Gallo, L. Pejchar. **2017**. Small-scale woodland reduction practices have neutral or negative short-term effects on birds and small mammals. Rangeland Ecology and Management 70:363-373. [PDF](publications/Bombaci_et_al_2017.pdf)

Miller, A., E. Goad, T. Gallo, L. Pejchar, L. Bailey, S. Reed. **2017**. The impact of exurban housing density on wintering birds. The Wilson Journal of Ornithology 129:85-97. [PDF](publications/Miller-et-al.-2017-Exurban-birds.pdf)

Riedl, H., D. Bennett, A. Mangan, L. Stinson, K. Wilkins, T. Gallo, L. Pejchar. **2017**. The Paradox of the Carnivorous Conservationist [book review]. Biological Conservation 205:11-112. [PDF](publications/Riedl-et-al-2016-book-review.pdf)

Gallo, T., L.T. Stinson, L. Pejchar. **2016**. Pinyon-juniper removal has long-term effects on mammals. Forest Ecology and Management 377:93-100. [PDF](publications/Gallo-et-al.-2016.pdf)

Gallo, T. and L. Pejchar. **2016**. Improving habitat for game animals has mixed consequences for biodiversity conservation. Biological Conservation 197:47:52. [PDF](publications/gallo_biocon_review.pdf)

Bombaci, S., C. Farr, T. Gallo, A. Mangan, L. Stinson, M. Kaushik, L. Pejchar. **2015**. Using Twitter to communicate conservation science beyond professional conferences. Conservation Biology 30:216-225. [PDF](publications/Bombaci_etal_2015_Twitter.pdf)

Gallo. T. and D. Waitt. **2011**. Creating a successful citizen science model to detect and report invasive species. BioScience 61:459-465. [PDF](publications/Gallo_2011_Bioscience.pdf)

