---
title: "Teaching"
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<style>
d-title, d-byline {
  display: none
}
</style>

<br>

## Teaching Philosophy

My teaching philosophy can be summed up in three words: inclusive, equal, and engaging.

1. **Inclusive** – Universities are increasingly characterized by a diverse student body. I am committed to creating a classroom climate that promotes and supports inclusivity. For example, I invite guest lecturers that represent the diversity of the student body, as well as design the course content and delivery to consider students' backgrounds and areas of interests. Providing diverse role models at the classroom podium and within lecture materials engages students and reinforces the idea that they too can become part of the next generation of leaders – regardless of race, ethnicity, ability, socioeconomic status, gender identity, or sexual orientation.

2. **Equal** – Feeling safe and welcome in the classroom leads to academic success. I create a classroom and lab environment that is built on collaboration and not competition. Students are encouraged to work together to solve problems and think critically. I aim to create a productive learning environment where, regardless of backgrounds and identities, students feel equal and respected.

3. **Engaging** – Feeling safe, welcome, and represented is my cornerstone to successful interaction with students. However, to encourage meaningful engagement with course content, I also incorporate readings from primary and popular literature to guide and stimulate discussion. Independent or group projects grounded in local ecosystems can also compliment learning in the classroom. As an urban ecologist, this approach is particularly well suited for more urban universities. Conducting projects in urban environments increases student knowledge about the natural world in which they spend their everyday lives, and promotes understanding and appreciation for the ecology of and in cities.

### Classes that Travis Teaches:

**Applied Ecology:** Fall and Spring semesters

**Conservation Biology:** Fall and Spring semesters in odd years (2021, 2023, 2025)

**Principles of Wildlife Ecology:** Spring semester in even years (2022, 2024, 2026)

**#rstats for Natural and Social Sciences:** Fall semester in even years (2022, 2024, 2026)